serverAddr = "__arg_server_address__"
serverPort = 7000

auth.method = "token"
auth.token = "__arg_auth_token__"

[[proxies]]
name = "__arg_proxy_name__"
type = "https"
localIP = "127.0.0.1"
localPort = 8123
subdomain = "__arg_subdomain__"
transport.useEncryption = true
transport.useCompression = true
